--[[

	This code was written by Scvrlae (@datonescvrlae) and is his property. Unauthorized use and/or
	distribution of this script is strongly prohibited! PLEASE ask first!

	  ██████  ▄████▄ ██▒   █▓ ██▀███   ██▓    ▄▄▄      ▓█████
	▒██    ▒ ▒██▀ ▀█▓██░   █▒▓██ ▒ ██▒▓██▒   ▒████▄    ▓█   ▀
	░ ▓██▄   ▒▓█    ▄▓██  █▒░▓██ ░▄█ ▒▒██░   ▒██  ▀█▄  ▒███
	  ▒   ██▒▒▓▓▄ ▄██▒▒██ █░░▒██▀▀█▄  ▒██░   ░██▄▄▄▄██ ▒▓█  ▄
	▒██████▒▒▒ ▓███▀ ░ ▒▀█░  ░██▓ ▒██▒░██████▒▓█   ▓██▒░▒████▒

	This script is part of the Vigorous framework owned and maintained by Scvrlae (@datonescvrlae).
	It is public and available for use by anyone for their games!

--]]

local Vigorous = require(game.ReplicatedStorage.Vigorous)
local module = {}

function module:Start(localDirectory: PlayerScripts | ServerScriptService)
       

	Vigorous.IsLoaded = true --// After loading set this key to true
end

return module
